########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
        
########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
 
include:
  ########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=udms - defined in .env
 
  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dozzle.yml
  - compose/$HOSTNAME/homepage.yml
  # MEDIA
  - compose/$HOSTNAME/plex.yml
  # MONITORING
  - compose/$HOSTNAME/uptime-kuma.yml
  # DOWNLOADERS
  - compose/$HOSTNAME/sabnzbd.yml
  # PVRS
  - compose/$HOSTNAME/radarr.yml
  - compose/$HOSTNAME/radarr-4k.yml
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/sonarr-4k.yml
  # COMPLEMENTARY APPS
  - compose/$HOSTNAME/bazarr.yml
  - compose/$HOSTNAME/tautulli.yml
  - compose/$HOSTNAME/recyclarr.yml