########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24        
        
########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  sonarr_api_key:
    file: $DOCKERDIR/secrets/sonarr_api_key
  sonarr_4k_api_key:
    file: $DOCKERDIR/secrets/sonarr_4k_api_key
  radarr_api_key:
    file: $DOCKERDIR/secrets/radarr_api_key
  radarr_4k_api_key:
    file: $DOCKERDIR/secrets/radarr_4k_api_key
 
include:
  ########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=udms - defined in .env
 
  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/traefik.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/vs-code.yml
  - compose/$HOSTNAME/traefik-access-log.yml
  - compose/$HOSTNAME/traefik-error-log.yml
  # FRONTEND
  # - compose/$HOSTNAME/homepage.yml
  - compose/$HOSTNAME/heimdall.yml
  # MEDIA
  - compose/$HOSTNAME/plex.yml
  # MEDIA REQUESTER
  - compose/$HOSTNAME/overseerr.yml
  # MONITORING
  - compose/$HOSTNAME/dozzle.yml
  - compose/$HOSTNAME/uptime-kuma.yml
  # DOWNLOADERS
  - compose/$HOSTNAME/sabnzbd.yml
  - compose/$HOSTNAME/rdt-client.yml
  # PVRS
  - compose/$HOSTNAME/prowlarr.yml
  - compose/$HOSTNAME/radarr.yml
  - compose/$HOSTNAME/radarr-4k.yml
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/sonarr-4k.yml
  # MEAL PLANNERS
  - compose/$HOSTNAME/mealie.yml
  # COMPLEMENTARY APPS
  - compose/$HOSTNAME/bazarr.yml
  - compose/$HOSTNAME/tautulli.yml
  - compose/$HOSTNAME/recyclarr.yml
  - compose/$HOSTNAME/plex-utils.yml
  - compose/$HOSTNAME/it-tools.yml