services:
  # Mealie - Meal Planner
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.8.0 # 
    container_name: mealie
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "downloads", "all"]
    networks:
      - t3_proxy
    deploy:
      resources:
        limits:
          memory: 1000M #   
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - $DOCKERDIR/appdata/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: true
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.screamingvoid.org
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.mealie-rtr.entrypoints=websecure"
      - "traefik.http.routers.mealie-rtr.rule=Host(`mealie.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.mealie-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.mealie-rtr.service=mealie-svc"
      - "traefik.http.services.mealie-svc.loadbalancer.server.port=9000"