services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    networks:
      - t3_proxy
      - default
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "all"]
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $DATADIR/media:/data/media # Media Folder 1
      #- $DATADIR/data2/media:/data/media2 # Media Folder 2
      - /dev/shm:/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      HOSTNAME: "Plex"
      PLEX_CLAIM_FILE: /run/secrets/plex_claim # Not required initially
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$SERVER_IP:32400/"
      ALLOWED_NETWORKS: $LOCAL_IPS
    secrets:
      - plex_claim
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=websecure"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      - "traefik.http.middlewares.add-plex.addPrefix.prefix=/web"
      # HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"        