services:
  # Recyclaar - Sonaar / Radaar Profile Sync from TRaSH-Guides

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "arrs", "all"]
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/recyclarr:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID 
      RECYCLARR_CREATE_CONFIG: true