services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "downloads", "all"]
    networks:
      - t3_proxy
      - default
    #ports:
    #  - "8084:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DATADIR/usenet:/data/usenet
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.sabnzbd-rtr.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.sabnzbd-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # HTTP Services
      - "traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc"
      - "traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080"