services:
  # Sonarr - TV Shows Management
  # Set url_base in sonarr settings if using PathPrefix
  sonarr-4k:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr-4k
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "arrs", "all"]
    networks:
      - t3_proxy
      - default
    ports:
      - "8990:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr-4k:/config
      - $DATADIR:/data/
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.sonarr-4k-rtr.entrypoints=websecure"
      - "traefik.http.routers.sonarr-4k-rtr.rule=Host(`sonarr-4k.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.sonarr-4k-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # HTTP Services
      - "traefik.http.routers.sonarr-4k-rtr.service=sonarr-4k-svc"
      - "traefik.http.services.sonarr-4k-svc.loadbalancer.server.port=8989"